plugins {
    id "com.gradleup.shadow" version "9.2.2"
    id "net.fabricmc.fabric-loom"
}

loom {
    def accessWidener = file("src/main/resources/minetogetherservers.accesswidener")
    if (accessWidener.exists()) {
        accessWidenerPath.set(accessWidener)
    }

    runs {
        client {
            client()
            ideConfigGenerated true
            runDir "runs/client"
        }
        server {
            server()
            ideConfigGenerated true
            runDir "runs/server"
        }
    }
}

configurations {
    commonJava {
        canBeResolved = true
        canBeConsumed = false
    }
    commonResources {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowLib
    implementation.extendsFrom shadowLib
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    implementation "net.creeperhost.polylib:polylib-fabric:${polylib_version}"

    commonJava project(path: ":common", configuration: "commonJava")
    commonResources project(path: ":common", configuration: "commonResources")

    shadowLib "blue.endless:jankson:${jankson_version}"
    shadowLib("net.creeperhost:MineTogetherLib:${mtlib_version}") {
        exclude group: "net.creeperhost", module: "MineTogetherSessions"
    }
    shadowLib("net.creeperhost:MineTogetherSessions:${mtsession_version}") {
        transitive = false
    }
    shadowLib "org.nanohttpd:nanohttpd:2.3.1"
    shadowLib "com.github.scribejava:scribejava-apis:6.9.0"
    shadowLib "com.github.scribejava:scribejava-core:6.9.0"
}

tasks.named("compileJava", JavaCompile) {
    dependsOn configurations.commonJava
    source configurations.commonJava
}

processResources {
    dependsOn configurations.commonResources
    from configurations.commonResources
    exclude "META-INF/accesstransformer.cfg"

    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from zipTree(jar.archiveFile)
    configurations = [project.configurations.shadowLib]
    archiveClassifier = null
    mergeServiceFiles()

    relocate "blue.endless", "net.creeperhost.minetogetherservers.repack.blue.endless"
    relocate "net.covers1624", "net.creeperhost.minetogetherservers.repack.net.covers1624"
    relocate "org.pircbotx", "net.creeperhost.minetogetherservers.repack.org.pircbotx"
    relocate "com.github.scribejava", "net.creeperhost.minetogetherservers.com.github.scribejava"
    relocate "fi.iki.elonen", "net.creeperhost.minetogetherservers.fi.iki.elonen"
    relocate "com.fasterxml.jackson", "net.creeperhost.minetogetherservers.com.fasterxml.jackson"
    relocate "net.creeperhost.minetogether.lib", "net.creeperhost.minetogetherservers.repack.minetogether.lib"
    relocate "net.creeperhost.minetogether.session", "net.creeperhost.minetogetherservers.repack.minetogether.session"
    archiveBaseName.set "${rootProject.archives_base_name}-${project.name}-${rootProject.minecraft_version}"
}

assemble {
    dependsOn shadowJar
}

jar {
    archiveClassifier = "raw"
}

sourcesJar {
    dependsOn configurations.commonJava
    from configurations.commonJava
    dependsOn configurations.commonResources
    from configurations.commonResources
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }
}
