import org.jetbrains.gradle.ext.ActionDelegationConfig.TestRunner

plugins {
    id "net.fabricmc.fabric-loom" version "1.15.5" apply false
    id "net.neoforged.moddev" version "2.0.141" apply false
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.4.1"
}

allprojects {
    apply plugin: "java-library"
    apply plugin: "maven-publish"

    base {
        archivesName = rootProject.archives_base_name
    }
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        mavenCentral()
        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
        maven {
            name "CreeperHost"
            url 'https://maven.creeperhost.net'
        }
        maven { url "https://maven.ftb.dev/releases" }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(25)
        withSourcesJar()
    }
}

afterEvaluate {
    idea.project.settings {
        delegateActions {
            testRunner = TestRunner.PLATFORM
        }
    }
}
