org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

minecraft_version=26.2
enabled_platforms=fabric,neoforge

archives_base_name=minetogetherserverlist
mod_version=6.3.4
maven_group=net.creeperhost.minetogetherservers

fabric_loader_version=0.19.3
fabric_api_version=0.158.0+26.2

neoforge_version=26.2.0.62
neo_form_version=26.2-2

polylib_version=26.2-2.0.10

jankson_version=1.2.1
mtlib_version=3.6
quack_version=0.4.10.105
mtsession_version=1.2.7
