modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CreeperHost/MineTogether/issues"
license = "GNU General Public License v3.0"

[[mods]]
    modId = "minetogetherservers"
    version = "${version}"
    displayName = "MineTogether Server List"
    authors = "covers1624, Gigabit101, Cloudhunter, CreeperHost!"
    description = ''''''

[[dependencies.minetogetherservers]]
    modId = "neoforge"
    type="required"
    versionRange = "[26.2.0.62,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogetherservers]]
    modId = "minecraft"
    type="required"
    versionRange = "[26.2,26.3)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogetherservers]]
    modId = "polylib"
    type="required"
    versionRange = "[2.0.10,)"
    ordering = "AFTER"
    side = "BOTH"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "minetogetherservers-neoforge.mixins.json"

[[mixins]]
config = "minetogetherservers-common.mixins.json"
